### ISSUE TITLE
Can't Get Resource Dictionary Items When Only Reading Bundles

### ISSUE THREAD

**Issue by reece-berens** [HISB-Libraries/fhir-ig-dotnet#11]
During the MDI update workflow, my EDRS system is only reading MDI to EDRS bundles, not generating them. Because of this, I cannot use the Subject or Certifier fields on certain items because the resources dictionary is only populated when you set FHIR objects on those fields. Since bundles are being sent to me from a different system and I don't create them, the resources dictionary is always empty in my system, so I can't use the Subject and Certifier fields. I can work around this issue by referencing the base FHIR resources and their IDs, but I just thought I'd bring up this issue since it is something I ran into.

**Comment by myungchoi** [comment]
BundleDocumentMdiAndEdrs now populates the resources in resource references in Composition from Bundle.Entry. 

Bundle bundle = [bundle read from update request];
BundleDocumentMdiAndEdrs mdiBundle = bundle. BundleDocumentMdiAndEdrs();

mdiBundle.Entry[0].resource (Composition) now has a dictionary (resources) populated with resources, which Subject and Certifier of Composition should be able to read.
